version: '3.7'

services:
  web:
      build: .
      # command: python /project/manage.py runserver 0.0.0.0:8000
      command: gunicorn book_store.wsgi -b 0.0.0.0:8000
      volumes: 
        - .:/project
      ports:
        - 8000:8000
      depends_on:
        - db
  db:
    image: postgres:15.4
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_PASSWORD=postgres
volumes:
  postgres_data:
  
  